title: Qebaptore.org
default_lang: de
author:
  name: Bugjake
  email: null
taxonomies:
  - category
  - tag
metadata: null
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
